/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import controller.KaryawanControler;
import controller.ProdukControler;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.Karyawan;
import model.Produk;

/**
 *
 * @author PUGA
 */
public class Inputdata extends javax.swing.JFrame {
    private KaryawanControler karyawan;
    private ProdukControler produk;
    /**
     * Creates new form Inputdata
     */
    public Inputdata() throws SQLException {
        initComponents();
        this.karyawan = new KaryawanControler();
        this.produk = new ProdukControler();
        this.ShowTableKaryawan();
        this.ShowTableProduk();
    }
    
    private void ShowTableKaryawan() throws SQLException {
        DefaultTableModel dtmKaryawan = new DefaultTableModel(new String[]
        {"ID Karyawan","Nama Karyawan"},0);
        dtmKaryawan.setRowCount(0); 
        
        for(Karyawan dp : this.karyawan.getDataKaryawan()){
            dtmKaryawan.addRow(new String[]{dp.getId_Karyawan().toString(), dp.getNama_Karyawan().toString()});
        }

        this.jtbldatakaryawan.setModel(dtmKaryawan);
    }
    
    private void ShowTableProduk() throws SQLException {
        DefaultTableModel dtmProduk = new DefaultTableModel(new String[]
        {"ID Produk","Jenis Produk","Harga Satuan","Stock"},0);
        dtmProduk.setRowCount(0); 
        
        for(Produk dp : this.produk.getDataProduk()){
            dtmProduk.addRow(new String[]{dp.getId_Produk().toString(), dp.getJenis().toString(), 
                dp.getHarga_satuan().toString(), dp.getStok().toString()});
        }

        this.jtbldatabarang.setModel(dtmProduk);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlinputdata = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlnamakaryawan = new javax.swing.JLabel();
        jlidkaryawan = new javax.swing.JLabel();
        jtidkaryawan = new javax.swing.JTextField();
        jtnamakaryawan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbldatakaryawan = new javax.swing.JTable();
        jldatakaryawan = new javax.swing.JLabel();
        jlidproduk = new javax.swing.JLabel();
        jljenisproduk = new javax.swing.JLabel();
        jlhargasatuan = new javax.swing.JLabel();
        jlstock = new javax.swing.JLabel();
        jtidproduk = new javax.swing.JTextField();
        jtjenisproduk = new javax.swing.JTextField();
        satuan = new javax.swing.JTextField();
        jtstock = new javax.swing.JTextField();
        btnSimpanproduk = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbldatabarang = new javax.swing.JTable();
        jldatabarang = new javax.swing.JLabel();
        jbupdateproduk = new javax.swing.JButton();
        jbdeleteproduk = new javax.swing.JButton();
        jbback = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jbdeletekaryawan = new javax.swing.JButton();
        jbupdatekaryawan = new javax.swing.JButton();
        jbsimpankaryawan = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jlinputdata.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jlinputdata.setText("INPUT DATA");

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabel1.setText("Karyawan");

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabel2.setText("Produk");

        jlnamakaryawan.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        jlnamakaryawan.setText("Nama Karyawan");

        jlidkaryawan.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        jlidkaryawan.setText("ID Karyawan");

        jtbldatakaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Karyawan", "Nama Karyawan"
            }
        ));
        jtbldatakaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbldatakaryawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbldatakaryawan);

        jldatakaryawan.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jldatakaryawan.setText("Data Karyawan");

        jlidproduk.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        jlidproduk.setText("ID Produk");

        jljenisproduk.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jljenisproduk.setText("Jenis Produk");

        jlhargasatuan.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jlhargasatuan.setText("Harga Satuan");

        jlstock.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jlstock.setText("Stock");

        btnSimpanproduk.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnSimpanproduk.setText("SIMPAN");
        btnSimpanproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanprodukActionPerformed(evt);
            }
        });

        jtbldatabarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Barang", "Jenis Produk", "Harga Satuan", "Stock"
            }
        ));
        jtbldatabarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbldatabarangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbldatabarang);

        jldatabarang.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jldatabarang.setText("Data Barang");

        jbupdateproduk.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jbupdateproduk.setText("UPDATE");
        jbupdateproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbupdateprodukActionPerformed(evt);
            }
        });

        jbdeleteproduk.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jbdeleteproduk.setText("DELETE");
        jbdeleteproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdeleteprodukActionPerformed(evt);
            }
        });

        jbback.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jbback.setText("BACK");
        jbback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbackActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton1.setText("TRANSAKSI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbdeletekaryawan.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jbdeletekaryawan.setText("DELETE");
        jbdeletekaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdeletekaryawanActionPerformed(evt);
            }
        });

        jbupdatekaryawan.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jbupdatekaryawan.setText("UPDATE");
        jbupdatekaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbupdatekaryawanActionPerformed(evt);
            }
        });

        jbsimpankaryawan.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbsimpankaryawan.setText("SIMPAN");
        jbsimpankaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsimpankaryawanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(171, 171, 171)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlinputdata)
                            .addComponent(jldatakaryawan)))
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlidkaryawan)
                                    .addComponent(jlnamakaryawan)
                                    .addComponent(jlhargasatuan)
                                    .addComponent(jlidproduk)
                                    .addComponent(jlstock)
                                    .addComponent(jljenisproduk)
                                    .addComponent(jbupdatekaryawan))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbsimpankaryawan)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtidkaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                            .addComponent(jtnamakaryawan)
                                            .addComponent(jtidproduk))
                                        .addComponent(satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtstock, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtjenisproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jbdeletekaryawan)
                            .addComponent(jbback))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jldatabarang)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jbupdateproduk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbdeleteproduk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSimpanproduk)))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jlinputdata)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jldatakaryawan, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlidkaryawan)
                            .addComponent(jtidkaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtnamakaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlnamakaryawan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbupdatekaryawan)
                            .addComponent(jbsimpankaryawan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbdeletekaryawan))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jldatabarang)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtidproduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlidproduk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtjenisproduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jljenisproduk))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(satuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlhargasatuan)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbupdateproduk)
                    .addComponent(btnSimpanproduk)
                    .addComponent(jbdeleteproduk)
                    .addComponent(jtstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlstock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbback)
                    .addComponent(jButton1))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanprodukActionPerformed
        Produk produk = new Produk();
        
        try {
                        
            produk.setId_Produk(Integer.parseInt(this.jtidproduk.getText()));
            produk.setJenis(this.jtjenisproduk.getText());
            produk.setHarga_satuan(Integer.parseInt(this.satuan.getText()));
            produk.setStok(Integer.parseInt(this.jtstock.getText()));
                        
            this.produk.getDataProduk();
            this.produk.insertProduk(produk);
            
            this.ShowTableProduk();
        } catch (SQLException  err) {
            System.out.println(err);
        }   
    }//GEN-LAST:event_btnSimpanprodukActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            new Viewtransaksi(Integer.parseInt(satuan.getText())).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Inputdata.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbackActionPerformed
        new Viewadmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbbackActionPerformed

    private void jbupdateprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbupdateprodukActionPerformed
        Produk produk = new Produk();
        try {
            
            produk.setId_Produk(Integer.parseInt(this.jtidproduk.getText()));
            produk.setJenis(this.jtjenisproduk.getText());
            produk.setHarga_satuan(Integer.parseInt(this.satuan.getText()));
            produk.setStok(Integer.parseInt(this.jtstock.getText()));
            
            this.produk.getDataProduk();
            this.produk.UpdateProduk(produk);
            this.ShowTableProduk();
        } catch (SQLException  err) {
            System.out.println(err);
        }
    }//GEN-LAST:event_jbupdateprodukActionPerformed

    private void jbsimpankaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsimpankaryawanActionPerformed
        Karyawan karyawan = new Karyawan();
        try {
            karyawan.setId_Karyawan(Integer.parseInt(this.jtidkaryawan.getText()));
            karyawan.setNama_Karyawan(this.jtnamakaryawan.getText());
            
            this.karyawan.getDataKaryawan();
            this.karyawan.insertKaryawan(karyawan);
            
            this.ShowTableKaryawan();
        } catch (SQLException  err) {
            System.out.println(err);
        }
    }//GEN-LAST:event_jbsimpankaryawanActionPerformed

    private void jbupdatekaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbupdatekaryawanActionPerformed
        Karyawan karyawan = new Karyawan();
        try {
            karyawan.setId_Karyawan(Integer.parseInt(this.jtidkaryawan.getText()));
            karyawan.setNama_Karyawan(this.jtnamakaryawan.getText());
            
            this.karyawan.getDataKaryawan();
            this.karyawan.UpdateKaryawan(karyawan);
            
            this.ShowTableKaryawan();
        } catch (SQLException  err) {
            System.out.println(err);
        }
    }//GEN-LAST:event_jbupdatekaryawanActionPerformed

    private void jbdeletekaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdeletekaryawanActionPerformed
        Karyawan karyawan = new Karyawan();
        try {
            
            this.jtbldatakaryawan.getSelectedRow();
            karyawan.setId_Karyawan(Integer.parseInt(jtbldatakaryawan.getValueAt(jtbldatakaryawan.getSelectedRow(), 0).toString()));
            
            this.karyawan.deleteKaryawan(karyawan);
            this.ShowTableKaryawan();
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jbdeletekaryawanActionPerformed

    private void jbdeleteprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdeleteprodukActionPerformed
        Produk produk = new Produk();
        try {
            
            this.jtbldatabarang.getSelectedRow();
            produk.setId_Produk(Integer.parseInt(jtbldatabarang.getValueAt(jtbldatabarang.getSelectedRow(), 0).toString()));
            
            this.produk.deleteProduk(produk);
            this.ShowTableProduk();
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jbdeleteprodukActionPerformed

    private void jtbldatakaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbldatakaryawanMouseClicked
        int baris = jtbldatakaryawan.getSelectedRow();
        this.jtidkaryawan.setText(jtbldatakaryawan.getValueAt(baris, 0 ).toString());
        this.jtnamakaryawan.setText(jtbldatakaryawan.getValueAt(baris, 1).toString());
    }//GEN-LAST:event_jtbldatakaryawanMouseClicked

    private void jtbldatabarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbldatabarangMouseClicked
        int baris = jtbldatabarang.getSelectedRow();
        this.jtidproduk.setText(jtbldatabarang.getValueAt(baris, 0 ).toString());
        this.jtjenisproduk.setText(jtbldatabarang.getValueAt(baris, 1).toString());
        this.satuan.setText(jtbldatabarang.getValueAt(baris, 2).toString());
        this.jtstock.setText(jtbldatabarang.getValueAt(baris, 3).toString());
    }//GEN-LAST:event_jtbldatabarangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inputdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inputdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inputdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inputdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    new Inputdata().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Inputdata.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpanproduk;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbback;
    private javax.swing.JButton jbdeletekaryawan;
    private javax.swing.JButton jbdeleteproduk;
    private javax.swing.JButton jbsimpankaryawan;
    private javax.swing.JButton jbupdatekaryawan;
    private javax.swing.JButton jbupdateproduk;
    private javax.swing.JLabel jldatabarang;
    private javax.swing.JLabel jldatakaryawan;
    private javax.swing.JLabel jlhargasatuan;
    private javax.swing.JLabel jlidkaryawan;
    private javax.swing.JLabel jlidproduk;
    private javax.swing.JLabel jlinputdata;
    private javax.swing.JLabel jljenisproduk;
    private javax.swing.JLabel jlnamakaryawan;
    private javax.swing.JLabel jlstock;
    private javax.swing.JTable jtbldatabarang;
    private javax.swing.JTable jtbldatakaryawan;
    private javax.swing.JTextField jtidkaryawan;
    private javax.swing.JTextField jtidproduk;
    private javax.swing.JTextField jtjenisproduk;
    private javax.swing.JTextField jtnamakaryawan;
    private javax.swing.JTextField jtstock;
    private javax.swing.JTextField satuan;
    // End of variables declaration//GEN-END:variables
}
