/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import controller.PembeliControler;
import controller.ProdukControler;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import model.Pembeli;
import model.Produk;

/**
 *
 * @author PUGA
 */
public class Viewtransaksi extends javax.swing.JFrame {
    private PembeliControler pembeli;
    private ProdukControler produk;
    private Integer spn;
    /**
     * Creates new form Viewtransaksi
     */
    private Integer hargatotal;
    
    public Viewtransaksi() 
    {
                
    }
    
    public Viewtransaksi(Integer x) throws SQLException {
        initComponents();
        this.pembeli = new PembeliControler();
        this.produk = new ProdukControler();
        this.hargatotal=0;
        this.spn=x;
        this.ShowTablePembeli();
    }
    private void ShowTablePembeli() throws SQLException {
        DefaultTableModel dtmPembeli = new DefaultTableModel(new String[]
        {"ID Pembeli","Nama Pembeli","No Telp"},0);
        dtmPembeli.setRowCount(0); 
        
        for(Pembeli dp : this.pembeli.getDataPembeli()){
            dtmPembeli.addRow(new String[]{dp.getId_Pembeli().toString(), dp.getNama_Pembeli().toString(), dp.getNo_telp().toString()});
        }

        this.jtbldata_pembeli.setModel(dtmPembeli);
    }
    
    private void showComboBoxFilm() throws SQLException {
        DefaultComboBoxModel dcbmProduk = new DefaultComboBoxModel();

        for (Produk f : this.produk.getDataProduk()) {
            dcbmProduk.addElement(f.getJenis());
        }
        this.jcjenis_produk.setModel(dcbmProduk);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlnama_pembeli = new javax.swing.JLabel();
        jlno_telp = new javax.swing.JLabel();
        jljenis_produk = new javax.swing.JLabel();
        jcjenis_produk = new javax.swing.JComboBox<>();
        jljumlah = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        jltotal_harga = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbldata_pembeli = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbldata_transaksi = new javax.swing.JTable();
        jtnama_pembeli = new javax.swing.JTextField();
        jtno_telp = new javax.swing.JTextField();
        jbinsert = new javax.swing.JButton();
        jldata_pembeli = new javax.swing.JLabel();
        jbtotal = new javax.swing.JButton();
        jbsimpan = new javax.swing.JButton();
        jldatatransaksi = new javax.swing.JLabel();
        jlidpembeli = new javax.swing.JLabel();
        jtidpembeli = new javax.swing.JTextField();
        jbback = new javax.swing.JButton();
        jbdeletepembeli = new javax.swing.JButton();
        jlnamakaryawan = new javax.swing.JLabel();
        jcnamakaryawan = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 51));

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 48)); // NOI18N
        jLabel1.setText("TRANSAKSI");

        jlnama_pembeli.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jlnama_pembeli.setText("Nama Pembeli");

        jlno_telp.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jlno_telp.setText("No Telp");

        jljenis_produk.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jljenis_produk.setText("Jenis Produk");

        jcjenis_produk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jljumlah.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jljumlah.setText("Jumlah");

        jltotal_harga.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jltotal_harga.setText("Total Harga");

        jtbldata_pembeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Pembeli", "Nama Pembeli", "No Telepon"
            }
        ));
        jtbldata_pembeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbldata_pembeliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbldata_pembeli);

        jtbldata_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Transaksi", "Pembeli", "Karyawan", "Jenis Produk", "Harga Total"
            }
        ));
        jScrollPane2.setViewportView(jtbldata_transaksi);

        jbinsert.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jbinsert.setText("INSERT");
        jbinsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbinsertActionPerformed(evt);
            }
        });

        jldata_pembeli.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jldata_pembeli.setText("Data Pembeli");

        jbtotal.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jbtotal.setText("TOTAL");
        jbtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtotalActionPerformed(evt);
            }
        });

        jbsimpan.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jbsimpan.setText("SIMPAN");

        jldatatransaksi.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jldatatransaksi.setText("Data Transaksi");

        jlidpembeli.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jlidpembeli.setText("ID Pembeli");

        jbback.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jbback.setText("BACK");
        jbback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbackActionPerformed(evt);
            }
        });

        jbdeletepembeli.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jbdeletepembeli.setText("DELETE");

        jlnamakaryawan.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jlnamakaryawan.setText("Nama Karyawan");

        jcnamakaryawan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcnamakaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcnamakaryawanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlno_telp)
                            .addComponent(jlnama_pembeli)
                            .addComponent(jljumlah)
                            .addComponent(jljenis_produk)
                            .addComponent(jlidpembeli)
                            .addComponent(jltotal_harga)
                            .addComponent(jbdeletepembeli)
                            .addComponent(jlnamakaryawan))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jcjenis_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbinsert)
                                        .addComponent(jtno_telp, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                        .addComponent(jtnama_pembeli, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                        .addComponent(jbtotal)
                                        .addComponent(jbsimpan)
                                        .addComponent(jtidpembeli))
                                    .addComponent(jcnamakaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(76, 76, 76)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jldata_pembeli, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jldatatransaksi, javax.swing.GroupLayout.Alignment.LEADING)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbback)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlidpembeli)
                            .addComponent(jtidpembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlnama_pembeli)
                            .addComponent(jtnama_pembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlno_telp)
                            .addComponent(jtno_telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jldata_pembeli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbinsert)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jldatatransaksi)
                            .addComponent(jlnamakaryawan)
                            .addComponent(jcnamakaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jljenis_produk)
                                    .addComponent(jcjenis_produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jljumlah)
                                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtotal))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jltotal_harga)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbsimpan)
                        .addGap(18, 18, 18)
                        .addComponent(jbback))
                    .addComponent(jbdeletepembeli))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbackActionPerformed
        try {
            new Inputdata().setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Viewtransaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbbackActionPerformed

    private void jbinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbinsertActionPerformed
        Pembeli pembeli = new Pembeli();
        try {
            pembeli.setId_Pembeli(Integer.parseInt(this.jtidpembeli.getText()));
            pembeli.setNama_Pembeli(this.jtnama_pembeli.getText());
            pembeli.setNo_telp(this.jtno_telp.getText());
            
            
            this.pembeli.getDataPembeli();
            this.pembeli.insertPembeli(pembeli);
            
            this.ShowTablePembeli();
        } catch (SQLException  err) {
            System.out.println(err);
        }
    }//GEN-LAST:event_jbinsertActionPerformed

    private void jtbldata_pembeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbldata_pembeliMouseClicked
        int baris = jtbldata_pembeli.getSelectedRow();
        this.jtidpembeli.setText(jtbldata_pembeli.getValueAt(baris, 0 ).toString());
        this.jtnama_pembeli.setText(jtbldata_pembeli.getValueAt(baris, 1 ).toString());
        this.jtno_telp.setText(jtbldata_pembeli.getValueAt(baris, 2).toString());
    }//GEN-LAST:event_jtbldata_pembeliMouseClicked

    private void jbtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtotalActionPerformed
        this.hargatotal += (Integer.parseInt(jumlah.getText())*spn);
            total.setText(this.hargatotal.toString());
    }//GEN-LAST:event_jbtotalActionPerformed

    private void jcnamakaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcnamakaryawanActionPerformed
        
    }//GEN-LAST:event_jcnamakaryawanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viewtransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viewtransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viewtransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viewtransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Viewtransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbback;
    private javax.swing.JButton jbdeletepembeli;
    private javax.swing.JButton jbinsert;
    private javax.swing.JButton jbsimpan;
    private javax.swing.JButton jbtotal;
    private javax.swing.JComboBox<String> jcjenis_produk;
    private javax.swing.JComboBox<String> jcnamakaryawan;
    private javax.swing.JLabel jldata_pembeli;
    private javax.swing.JLabel jldatatransaksi;
    private javax.swing.JLabel jlidpembeli;
    private javax.swing.JLabel jljenis_produk;
    private javax.swing.JLabel jljumlah;
    private javax.swing.JLabel jlnama_pembeli;
    private javax.swing.JLabel jlnamakaryawan;
    private javax.swing.JLabel jlno_telp;
    private javax.swing.JLabel jltotal_harga;
    private javax.swing.JTable jtbldata_pembeli;
    private javax.swing.JTable jtbldata_transaksi;
    private javax.swing.JTextField jtidpembeli;
    private javax.swing.JTextField jtnama_pembeli;
    private javax.swing.JTextField jtno_telp;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
